generate:
  n_samples: 2000
  churn_rate: 0.3
  output: data/raw/churn_raw.csv

preprocess:
  test_size: 0.2
  random_state: 42
  output_train: data/processed/train.csv
  output_test: data/processed/test.csv

train:
  model_type: random_forest
  random_state: 42
  n_estimators: 300
  max_depth: 10
  model_output: models/churn_model.joblib

evaluate:
  metrics_output: metrics/metrics.json